#Java Deployment settings
deployment.security.level=MEDIUM
deployment.webjava.enabled=true
deployment.manifest.attributes.check=false
deployment.security.askgrantdialog.show=true
deployment.security.askgrantdialog.notinca=true
deployment.browser.path=/usr/bin/firefox
