### https://github.com/jburanen/docker-java-apples

services:
  docker-java-apples:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VNC_PASSWORD: ${VNC_PASSWORD:-docker}
    platform: linux/amd64
    container_name: docker-java-apples
    ports:
      - "0.0.0.0:5901:5901"
      - "0.0.0.0:6080:6080"
    restart: unless-stopped
